import ExcelJS from 'exceljs';
import { env } from '../config/env';
import { AppError } from '../errors/AppError';
import { formatDisplayDate, toDateOnly, todayInTimezone } from '../lib/dates';
import { currentLocale, INTL_LOCALES, type Locale } from '../lib/locale';
import { formatMoney } from '../lib/money';
import {
  drawFooters,
  drawHeader,
  drawTable,
  PAGE_MARGIN,
  renderToBuffer,
  type PdfColumn,
} from '../lib/pdf';
import { tenantRepository } from '../repositories/tenant.repository';
import type { ExportFormat, ReportId, ReportRange } from '../validators/report.schemas';
import { reportService } from './report.service';

/**
 * Downloadable reports (`GET /reports/:report/export?format=xlsx|pdf`): the same rows and totals
 * as the JSON reports, laid out as an Excel sheet (real numbers and dates, frozen header,
 * filters) or a landscape PDF with the Solvia header. Texts follow the request language.
 */

type Kind = 'text' | 'money' | 'number' | 'date';
type Cell = string | number | null;

interface ExportColumn {
  header: string;
  kind: Kind;
  /** Relative width: PDF columns share the page width in this proportion; Excel uses it ×6.5. */
  weight: number;
}

interface Layout {
  title: string;
  dated: boolean;
  columns: ExportColumn[];
  rows: Cell[][];
  /** Bold last line; null cells stay empty. */
  totals: Cell[] | null;
  empty: string;
}

const TEXT = {
  es: {
    tagline: 'Créditos y cobranzas',
    total: 'Total',
    walkIn: 'Cliente de paso',
    voided: 'anulada',
    snapshot: 'Stock al',
    footer: (page: number, pages: number) => `Generado por Solvia  |  Página ${page} de ${pages}`,
    titles: {
      'sales-by-customer': 'Ventas por cliente',
      'sales-by-product': 'Ventas por producto',
      'collections-by-customer': 'Cobros por cliente',
      stock: 'Stock y valor',
      shortages: 'Vendido sin stock',
    },
    empty: {
      'sales-by-customer': 'No hay ventas en esas fechas.',
      'sales-by-product': 'No hay ventas en esas fechas.',
      'collections-by-customer': 'No hay pagos en esas fechas.',
      stock: 'No hay productos que lleven la cuenta de su stock.',
      shortages: 'En esas fechas no se vendió nada sin stock.',
    },
    columns: {
      customer: 'Cliente',
      product: 'Producto',
      code: 'Código',
      sold: 'Vendido',
      sales: 'Ventas',
      inSales: 'En ventas',
      cash: 'Al contado',
      credit: 'Fiado',
      lastSale: 'Última venta',
      collected: 'Te pagó',
      payments: 'Pagos',
      yape: 'Yape',
      plin: 'Plin',
      cashMethod: 'Efectivo',
      transfer: 'Transferencia',
      lastPayment: 'Último pago',
      quantity: 'Cantidad',
      unit: 'Unidad',
      cost: 'Costo',
      profit: 'Ganancia',
      status: 'Estado',
      stock: 'Quedan',
      minStock: 'Avisar con',
      unitCost: 'Costo c/u',
      price: 'Precio',
      value: 'Vale (a costo)',
      retail: 'Vale (a precio de venta)',
      when: 'Cuándo',
      sale: 'Venta',
      soldUnits: 'Vendiste',
      missing: 'Faltaban',
      balanceAfter: 'Stock quedó en',
    },
    stockStatus: { out: 'Sin stock', low: 'Por acabarse', ok: 'Bien' },
    units: {
      unit: 'Unidad',
      kg: 'Kilo',
      liter: 'Litro',
      box: 'Caja',
      pack: 'Paquete',
      dozen: 'Docena',
      meter: 'Metro',
    },
  },
  en: {
    tagline: 'Credit & collections',
    total: 'Total',
    walkIn: 'Walk-in customer',
    voided: 'voided',
    snapshot: 'Stock on',
    footer: (page: number, pages: number) => `Generated by Solvia  |  Page ${page} of ${pages}`,
    titles: {
      'sales-by-customer': 'Sales by customer',
      'sales-by-product': 'Sales by product',
      'collections-by-customer': 'Payments by customer',
      stock: 'Stock and value',
      shortages: 'Sold without stock',
    },
    empty: {
      'sales-by-customer': 'No sales in those dates.',
      'sales-by-product': 'No sales in those dates.',
      'collections-by-customer': 'No payments in those dates.',
      stock: 'No products keep count of their stock.',
      shortages: 'Nothing was sold without stock in those dates.',
    },
    columns: {
      customer: 'Customer',
      product: 'Product',
      code: 'Code',
      sold: 'Sold',
      sales: 'Sales',
      inSales: 'In sales',
      cash: 'Cash',
      credit: 'On credit',
      lastSale: 'Last sale',
      collected: 'Paid you',
      payments: 'Payments',
      yape: 'Yape',
      plin: 'Plin',
      cashMethod: 'Cash',
      transfer: 'Bank transfer',
      lastPayment: 'Last payment',
      quantity: 'Quantity',
      unit: 'Unit',
      cost: 'Cost',
      profit: 'Profit',
      status: 'Status',
      stock: 'Left',
      minStock: 'Alert at',
      unitCost: 'Unit cost',
      price: 'Price',
      value: 'Worth (at cost)',
      retail: 'Worth (at sale price)',
      when: 'When',
      sale: 'Sale',
      soldUnits: 'You sold',
      missing: 'Missing',
      balanceAfter: 'Stock left at',
    },
    stockStatus: { out: 'Out of stock', low: 'Running low', ok: 'Fine' },
    units: {
      unit: 'Unit',
      kg: 'Kilo',
      liter: 'Liter',
      box: 'Box',
      pack: 'Pack',
      dozen: 'Dozen',
      meter: 'Meter',
    },
  },
} satisfies Record<Locale, unknown>;

type Text = (typeof TEXT)[Locale];

const col = (header: string, kind: Kind, weight: number): ExportColumn => ({
  header,
  kind,
  weight,
});

/** Local date and time of a timestamp, e.g. "24/09/2026 11:58". */
function localDateTime(iso: string, locale: Locale): string {
  return new Intl.DateTimeFormat(INTL_LOCALES[locale], {
    timeZone: env.APP_TIMEZONE,
    dateStyle: 'short',
    timeStyle: 'short',
  }).format(new Date(iso));
}

async function buildLayout(report: ReportId, range: ReportRange, text: Text): Promise<Layout> {
  const c = text.columns;
  const locale = currentLocale();
  switch (report) {
    case 'sales-by-customer': {
      const data = await reportService.salesByCustomer(range);
      return {
        title: text.titles[report],
        dated: true,
        columns: [
          col(c.customer, 'text', 5),
          col(c.sold, 'money', 2.2),
          col(c.sales, 'number', 1.4),
          col(c.cash, 'money', 2.2),
          col(c.credit, 'money', 2.2),
          col(c.lastSale, 'date', 2),
        ],
        rows: data.rows.map((row) => [
          row.name ?? text.walkIn,
          row.total,
          row.sales,
          row.cash,
          row.credit,
          row.lastSale,
        ]),
        totals: [
          text.total,
          data.totals.total,
          data.totals.sales,
          data.totals.cash,
          data.totals.credit,
          null,
        ],
        empty: text.empty[report],
      };
    }
    case 'sales-by-product': {
      const data = await reportService.salesByProduct(range);
      return {
        title: text.titles[report],
        dated: true,
        columns: [
          col(c.product, 'text', 5),
          col(c.sold, 'money', 2.2),
          col(c.quantity, 'number', 1.6),
          col(c.unit, 'text', 1.6),
          col(c.cost, 'money', 2.2),
          col(c.profit, 'money', 2.2),
          col(c.inSales, 'number', 1.4),
        ],
        rows: data.rows.map((row) => [
          row.name,
          row.revenue,
          row.quantity,
          text.units[row.unit as keyof Text['units']] ?? row.unit,
          row.cost,
          row.profit,
          row.sales,
        ]),
        totals: [
          text.total,
          data.totals.revenue,
          null,
          null,
          data.totals.cost,
          data.totals.profit,
          null,
        ],
        empty: text.empty[report],
      };
    }
    case 'collections-by-customer': {
      const data = await reportService.collectionsByCustomer(range);
      return {
        title: text.titles[report],
        dated: true,
        columns: [
          col(c.customer, 'text', 4.4),
          col(c.collected, 'money', 2.2),
          col(c.payments, 'number', 1.3),
          col(c.yape, 'money', 2),
          col(c.plin, 'money', 2),
          col(c.cashMethod, 'money', 2),
          col(c.transfer, 'money', 2.2),
          col(c.lastPayment, 'date', 2),
        ],
        rows: data.rows.map((row) => [
          row.name,
          row.amount,
          row.payments,
          row.yape,
          row.plin,
          row.cash,
          row.bankTransfer,
          row.lastPayment,
        ]),
        totals: [
          text.total,
          data.totals.amount,
          data.totals.payments,
          data.totals.yape,
          data.totals.plin,
          data.totals.cash,
          data.totals.bankTransfer,
          null,
        ],
        empty: text.empty[report],
      };
    }
    case 'stock': {
      const data = await reportService.stock();
      return {
        title: text.titles[report],
        dated: false,
        columns: [
          col(c.product, 'text', 4.4),
          col(c.code, 'text', 2.4),
          col(c.status, 'text', 1.8),
          col(c.stock, 'number', 1.4),
          col(c.unit, 'text', 1.4),
          col(c.minStock, 'number', 1.4),
          col(c.unitCost, 'money', 1.8),
          col(c.price, 'money', 1.8),
          col(c.value, 'money', 2.2),
          col(c.retail, 'money', 2.6),
        ],
        rows: data.rows.map((row) => [
          row.name,
          row.code,
          text.stockStatus[row.status],
          row.stock,
          text.units[row.unit],
          row.minStock,
          row.cost,
          row.price,
          row.value,
          row.retail,
        ]),
        totals: [
          text.total,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          data.totals.value,
          data.totals.retail,
        ],
        empty: text.empty[report],
      };
    }
    case 'shortages': {
      const data = await reportService.shortages(range);
      return {
        title: text.titles[report],
        dated: true,
        columns: [
          col(c.when, 'text', 2.6),
          col(c.product, 'text', 4),
          col(c.missing, 'number', 1.5),
          col(c.soldUnits, 'number', 1.5),
          col(c.balanceAfter, 'number', 1.8),
          col(c.sale, 'text', 2),
          col(c.customer, 'text', 3.4),
        ],
        rows: data.rows.map((row) => [
          localDateTime(row.at, locale),
          row.product,
          row.shortage,
          row.quantity,
          row.balanceAfter,
          `#${row.sale.number}${row.sale.status === 'voided' ? ` (${text.voided})` : ''}`,
          row.customer ?? text.walkIn,
        ]),
        totals: [text.total, null, data.totals.units, null, null, null, null],
        empty: text.empty[report],
      };
    }
  }
}

const EXCEL_TITLE_ROWS = 3;

function currencySymbol(locale: Locale): string {
  return (
    new Intl.NumberFormat(INTL_LOCALES[locale], { style: 'currency', currency: env.CURRENCY })
      .formatToParts(0)
      .find((part) => part.type === 'currency')?.value ?? env.CURRENCY
  );
}

async function toExcel(layout: Layout, subtitle: string, locale: Locale): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Solvia';
  workbook.created = new Date();
  // Excel sheet names: at most 31 characters, no []:*?/\
  const sheet = workbook.addWorksheet(layout.title.replace(/[[\]:*?/\\]/g, ' ').slice(0, 31), {
    views: [{ state: 'frozen', ySplit: EXCEL_TITLE_ROWS + 1 }],
  });
  const moneyFormat = `"${currencySymbol(locale)}" #,##0.00`;
  const dateFormat = locale === 'es' ? 'dd/mm/yyyy' : 'mm/dd/yyyy';

  sheet.columns = layout.columns.map((column) => ({
    width: Math.max(13, Math.round(column.weight * 6.5)),
  }));
  sheet.getCell('A1').value = layout.title;
  sheet.getCell('A1').font = { bold: true, size: 14, color: { argb: 'FF0F766E' } };
  sheet.getCell('A2').value = subtitle;
  sheet.getCell('A2').font = { size: 10, color: { argb: 'FF6B7280' } };

  const header = sheet.getRow(EXCEL_TITLE_ROWS + 1);
  header.values = layout.columns.map((column) => column.header);
  header.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  header.eachCell((cell) => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F766E' } };
    cell.alignment = { vertical: 'middle' };
  });
  header.height = 20;

  const toCell = (value: Cell, kind: Kind) =>
    value === null ? null : kind === 'date' ? toDateOnly(String(value)) : value;
  const addRow = (values: Cell[]) => {
    const row = sheet.addRow(
      values.map((value, index) => toCell(value, layout.columns[index]!.kind)),
    );
    layout.columns.forEach((column, index) => {
      const cell = row.getCell(index + 1);
      if (column.kind === 'money') cell.numFmt = moneyFormat;
      if (column.kind === 'date') cell.numFmt = dateFormat;
      if (column.kind !== 'text') cell.alignment = { horizontal: 'right' };
    });
    return row;
  };

  for (const values of layout.rows) addRow(values);
  if (layout.rows.length > 0) {
    sheet.autoFilter = {
      from: { row: EXCEL_TITLE_ROWS + 1, column: 1 },
      to: { row: EXCEL_TITLE_ROWS + 1 + layout.rows.length, column: layout.columns.length },
    };
    if (layout.totals) {
      const totals = addRow(layout.totals);
      totals.font = { bold: true };
      totals.eachCell((cell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF0FDFA' } };
        cell.border = { top: { style: 'thin', color: { argb: 'FF0F766E' } } };
      });
    }
  } else {
    sheet.addRow([layout.empty]).font = { italic: true, color: { argb: 'FF6B7280' } };
  }

  return Buffer.from(await workbook.xlsx.writeBuffer());
}

function toPdf(layout: Layout, subtitle: string, text: Text, locale: Locale): Promise<Buffer> {
  const money = (value: number) => formatMoney(value, env.CURRENCY, locale);
  const number = new Intl.NumberFormat(INTL_LOCALES[locale], { maximumFractionDigits: 3 });
  const format = (value: Cell, kind: Kind) => {
    if (value === null) return '';
    if (kind === 'money') return money(Number(value));
    if (kind === 'number') return number.format(Number(value));
    if (kind === 'date') return formatDisplayDate(toDateOnly(String(value)), locale);
    return String(value);
  };

  return renderToBuffer((doc) => {
    drawHeader(doc, { tagline: text.tagline, title: layout.title, subtitle });
    const available = doc.page.width - PAGE_MARGIN * 2;
    const weights = layout.columns.reduce((sum, column) => sum + column.weight, 0);
    const columns: PdfColumn[] = layout.columns.map((column) => ({
      header: column.header,
      width: Math.floor((available * column.weight) / weights),
      align: column.kind === 'text' ? 'left' : 'right',
    }));
    drawTable(
      doc,
      columns,
      layout.rows.map((row) =>
        row.map((value, index) => format(value, layout.columns[index]!.kind)),
      ),
      layout.empty,
      layout.totals && layout.rows.length > 0
        ? layout.totals.map((value, index) => format(value, layout.columns[index]!.kind))
        : null,
    );
    drawFooters(doc, text.footer);
  }, 'landscape');
}

export const reportExportService = {
  async export(report: ReportId, range: ReportRange, format: ExportFormat) {
    const tenant = await tenantRepository.findCurrent();
    if (!tenant) throw AppError.notFound('Tenant');
    const locale = currentLocale();
    const text = TEXT[locale];
    const layout = await buildLayout(report, range, text);
    const today = todayInTimezone(env.APP_TIMEZONE);
    const when = layout.dated
      ? range.from.getTime() === range.to.getTime()
        ? formatDisplayDate(range.from, locale)
        : `${formatDisplayDate(range.from, locale)} – ${formatDisplayDate(range.to, locale)}`
      : `${text.snapshot} ${formatDisplayDate(today, locale)}`;
    const subtitle = `${tenant.name}  |  ${when}`;

    const buffer =
      format === 'xlsx'
        ? await toExcel(layout, subtitle, locale)
        : await toPdf(layout, subtitle, text, locale);
    const slug = layout.title
      .normalize('NFD')
      .replace(/[̀-ͯ]/g, '')
      .replace(/[^a-z0-9]+/gi, '-')
      .toLowerCase();
    const period = layout.dated
      ? `-${range.from.toISOString().slice(0, 10)}-${range.to.toISOString().slice(0, 10)}`
      : `-${today.toISOString().slice(0, 10)}`;
    return {
      buffer,
      fileName: `solvia-${slug}${period}.${format}`,
      contentType:
        format === 'xlsx'
          ? 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
          : 'application/pdf',
    };
  },
};
