import PDFDocument from 'pdfkit';
import { env } from '../config/env';
import { outstandingAmount } from '../domain/receivableStatus';
import { AppError } from '../errors/AppError';
import { formatDisplayDate, todayInTimezone } from '../lib/dates';
import { formatMoney, roundMoney, toNumber } from '../lib/money';
import { customerRepository } from '../repositories/customer.repository';
import { tenantRepository } from '../repositories/tenant.repository';
import { notificationService } from './notification.service';
import { settingsService } from './settings.service';
import { storageService } from './storage.service';

type PdfDoc = InstanceType<typeof PDFDocument>;

const BRAND_COLOR = '#0F766E';
const TEXT_COLOR = '#1F2937';
const MUTED_COLOR = '#6B7280';
const BORDER_COLOR = '#E5E7EB';
const PAGE_MARGIN = 50;

interface Column {
  header: string;
  width: number;
  align?: 'left' | 'right';
}

const METHOD_LABELS: Record<string, string> = {
  yape: 'Yape',
  plin: 'Plin',
  cash: 'Cash',
  bank_transfer: 'Bank transfer',
};

function renderToBuffer(build: (doc: PdfDoc) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    try {
      build(doc);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

function drawHeader(doc: PdfDoc, businessName: string, generatedOn: Date) {
  const width = doc.page.width;
  doc.rect(0, 0, width, 90).fill(BRAND_COLOR);
  doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(26).text('Solvia', PAGE_MARGIN, 28);
  doc.font('Helvetica').fontSize(10).text('Credit & collections', PAGE_MARGIN, 58);
  doc
    .font('Helvetica-Bold')
    .fontSize(14)
    .text('Account Statement', PAGE_MARGIN, 30, { width: width - PAGE_MARGIN * 2, align: 'right' });
  doc
    .font('Helvetica')
    .fontSize(10)
    .text(`${businessName}  |  ${formatDisplayDate(generatedOn)}`, PAGE_MARGIN, 52, {
      width: width - PAGE_MARGIN * 2,
      align: 'right',
    });
  doc.fillColor(TEXT_COLOR);
  doc.y = 115;
}

function drawSectionTitle(doc: PdfDoc, title: string) {
  ensureSpace(doc, 40);
  doc.moveDown(0.8);
  doc.font('Helvetica-Bold').fontSize(12).fillColor(BRAND_COLOR).text(title, PAGE_MARGIN);
  doc.moveDown(0.4);
  doc.fillColor(TEXT_COLOR);
}

function ensureSpace(doc: PdfDoc, height: number) {
  if (doc.y + height > doc.page.height - PAGE_MARGIN - 20) {
    doc.addPage();
    doc.y = PAGE_MARGIN;
  }
}

function drawRow(
  doc: PdfDoc,
  columns: Column[],
  values: string[],
  options: { bold?: boolean; fill?: string },
) {
  const rowHeight = 20;
  ensureSpace(doc, rowHeight);
  const top = doc.y;
  const tableWidth = columns.reduce((sum, column) => sum + column.width, 0);
  if (options.fill) {
    doc.rect(PAGE_MARGIN, top, tableWidth, rowHeight).fill(options.fill);
  }
  doc
    .font(options.bold ? 'Helvetica-Bold' : 'Helvetica')
    .fontSize(9)
    .fillColor(TEXT_COLOR);
  let x = PAGE_MARGIN;
  columns.forEach((column, index) => {
    doc.text(values[index] ?? '', x + 4, top + 6, {
      width: column.width - 8,
      align: column.align ?? 'left',
      lineBreak: false,
      ellipsis: true,
    });
    x += column.width;
  });
  doc
    .moveTo(PAGE_MARGIN, top + rowHeight)
    .lineTo(PAGE_MARGIN + tableWidth, top + rowHeight)
    .strokeColor(BORDER_COLOR)
    .lineWidth(0.5)
    .stroke();
  doc.y = top + rowHeight;
}

function drawTable(doc: PdfDoc, columns: Column[], rows: string[][], emptyMessage: string) {
  drawRow(
    doc,
    columns,
    columns.map((column) => column.header),
    { bold: true, fill: '#F3F4F6' },
  );
  if (rows.length === 0) {
    doc
      .moveDown(0.5)
      .font('Helvetica-Oblique')
      .fontSize(9)
      .fillColor(MUTED_COLOR)
      .text(emptyMessage, PAGE_MARGIN);
    doc.fillColor(TEXT_COLOR);
    return;
  }
  for (const row of rows) {
    drawRow(doc, columns, row, {});
  }
}

function drawFooters(doc: PdfDoc) {
  const range = doc.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(MUTED_COLOR)
      .text(
        `Generated by Solvia  |  Page ${index + 1} of ${range.count}`,
        PAGE_MARGIN,
        doc.page.height - PAGE_MARGIN + 10,
        { width: doc.page.width - PAGE_MARGIN * 2, align: 'center', lineBreak: false },
      );
  }
}

export const statementService = {
  /** Builds the PDF account statement for a customer of the current tenant. */
  async generatePdf(customerId: string) {
    const [tenant, customer] = await Promise.all([
      tenantRepository.findCurrent(),
      customerRepository.findByIdWithHistory(customerId),
    ]);
    if (!customer) throw AppError.notFound('Customer');
    if (!tenant) throw AppError.notFound('Tenant');

    const currency = env.CURRENCY;
    const money = (value: number) => formatMoney(value, currency);
    const today = todayInTimezone(env.APP_TIMEZONE);

    const receivables = customer.receivables.map((receivable) => {
      const totalAmount = toNumber(receivable.totalAmount);
      const paidAmount = toNumber(receivable.paidAmount);
      return {
        ...receivable,
        totalAmount,
        paidAmount,
        outstanding: outstandingAmount({ totalAmount, paidAmount }),
      };
    });
    const payments = customer.receivables
      .flatMap((receivable) => receivable.payments.map((payment) => ({ ...payment, receivable })))
      .sort((a, b) => b.date.getTime() - a.date.getTime());

    const totals = {
      billed: roundMoney(receivables.reduce((sum, item) => sum + item.totalAmount, 0)),
      paid: roundMoney(receivables.reduce((sum, item) => sum + item.paidAmount, 0)),
      outstanding: roundMoney(receivables.reduce((sum, item) => sum + item.outstanding, 0)),
      overdue: roundMoney(
        receivables
          .filter((item) => item.status === 'overdue')
          .reduce((sum, item) => sum + item.outstanding, 0),
      ),
    };

    const buffer = await renderToBuffer((doc) => {
      drawHeader(doc, tenant.name, today);

      doc.font('Helvetica-Bold').fontSize(11).text('Customer');
      doc.font('Helvetica').fontSize(10).fillColor(TEXT_COLOR).text(customer.name);
      doc.fillColor(MUTED_COLOR).text(customer.phone);
      if (customer.documentId) doc.text(`ID: ${customer.documentId}`);
      doc.fillColor(TEXT_COLOR);

      drawSectionTitle(doc, 'Summary');
      drawTable(
        doc,
        [
          { header: 'Total billed', width: 124, align: 'right' },
          { header: 'Total paid', width: 124, align: 'right' },
          { header: 'Outstanding', width: 124, align: 'right' },
          { header: 'Overdue', width: 123, align: 'right' },
        ],
        [
          [
            money(totals.billed),
            money(totals.paid),
            money(totals.outstanding),
            money(totals.overdue),
          ],
        ],
        '',
      );

      drawSectionTitle(doc, 'Receivables');
      drawTable(
        doc,
        [
          { header: 'Description', width: 135 },
          { header: 'Issued', width: 62 },
          { header: 'Due', width: 62 },
          { header: 'Total', width: 64, align: 'right' },
          { header: 'Paid', width: 64, align: 'right' },
          { header: 'Balance', width: 64, align: 'right' },
          { header: 'Status', width: 44 },
        ],
        receivables.map((item) => [
          item.description,
          formatDisplayDate(item.issueDate),
          formatDisplayDate(item.dueDate),
          money(item.totalAmount),
          money(item.paidAmount),
          money(item.outstanding),
          item.status,
        ]),
        'No receivables registered.',
      );

      drawSectionTitle(doc, 'Payment history');
      drawTable(
        doc,
        [
          { header: 'Date', width: 90 },
          { header: 'Receivable', width: 215 },
          { header: 'Method', width: 90 },
          { header: 'Amount', width: 100, align: 'right' },
        ],
        payments.map((payment) => [
          formatDisplayDate(payment.date),
          payment.receivable.description,
          METHOD_LABELS[payment.method] ?? payment.method,
          money(toNumber(payment.amount)),
        ]),
        'No payments registered yet.',
      );

      drawFooters(doc);
    });

    const safeName = customer.name.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
    return {
      buffer,
      fileName: `solvia-statement-${safeName}.pdf`,
      customer,
      tenant,
      totals,
      today,
    };
  },

  /**
   * Generates the statement, stores it and sends it to the customer via WhatsApp.
   * `receivableId` links the notification log entry; defaults to the most recent receivable.
   */
  async sendStatement(customerId: string, receivableId?: string) {
    const { buffer, customer, tenant, totals, today } = await this.generatePdf(customerId);
    const linkedReceivableId = receivableId ?? customer.receivables[0]?.id;
    if (!linkedReceivableId) {
      throw AppError.unprocessable('The customer has no receivables to report');
    }

    const relativeUrl = await storageService.saveStatement(buffer);
    const statementUrl = storageService.toAbsoluteUrl(relativeUrl);
    const notification = await notificationService.sendWhatsApp({
      receivableId: linkedReceivableId,
      to: customer.phone,
      templateType: 'statement',
      templateText: await settingsService.getTemplateText('statement'),
      variables: {
        name: customer.name,
        business: tenant.name,
        amount: formatMoney(totals.outstanding, env.CURRENCY),
        date: formatDisplayDate(today),
        statementUrl,
      },
    });
    return { statementUrl: relativeUrl, notification };
  },
};
