import { env } from '../config/env';
import {
  drawFooters,
  drawHeader,
  drawSectionTitle,
  drawTable,
  MUTED_COLOR,
  renderToBuffer,
  TEXT_COLOR,
} from '../lib/pdf';
import { outstandingAmount } from '../domain/receivableStatus';
import { AppError } from '../errors/AppError';
import { formatDisplayDate, todayInTimezone } from '../lib/dates';
import { currentLocale, type Locale } from '../lib/locale';
import { formatMoney, roundMoney, toNumber } from '../lib/money';
import { customerRepository } from '../repositories/customer.repository';
import { tenantRepository } from '../repositories/tenant.repository';
import { whatsAppChatUrl } from '../lib/whatsapp';
import { whatsAppProvider } from '../providers/whatsapp';
import { notificationService } from './notification.service';
import { settingsService } from './settings.service';
import { storageService } from './storage.service';

/** Every text printed on the statement, in each supported language. */
const STRINGS = {
  en: {
    tagline: 'Credit & collections',
    title: 'Account Statement',
    customer: 'Customer',
    id: 'ID',
    summary: 'Summary',
    billed: 'Total billed',
    paid: 'Total paid',
    outstanding: 'Outstanding',
    overdue: 'Overdue',
    receivables: 'Receivables',
    description: 'Description',
    issued: 'Issued',
    due: 'Due',
    total: 'Total',
    paidShort: 'Paid',
    balance: 'Balance',
    status: 'Status',
    noReceivables: 'No receivables registered.',
    payments: 'Payment history',
    date: 'Date',
    receivable: 'Receivable',
    method: 'Method',
    amount: 'Amount',
    noPayments: 'No payments registered yet.',
    footer: (page: number, pages: number) => `Generated by Solvia  |  Page ${page} of ${pages}`,
    fileName: 'statement',
    methods: { yape: 'Yape', plin: 'Plin', cash: 'Cash', bank_transfer: 'Bank transfer' },
    statuses: { pending: 'Pending', partial: 'Partial', paid: 'Paid', overdue: 'Overdue' },
  },
  es: {
    tagline: 'Créditos y cobranzas',
    title: 'Estado de cuenta',
    customer: 'Cliente',
    id: 'Doc.',
    summary: 'Resumen',
    billed: 'Total facturado',
    paid: 'Total pagado',
    outstanding: 'Saldo pendiente',
    overdue: 'Vencido',
    receivables: 'Deudas',
    description: 'Descripción',
    issued: 'Emisión',
    due: 'Vencimiento',
    total: 'Total',
    paidShort: 'Pagado',
    balance: 'Saldo',
    status: 'Estado',
    noReceivables: 'No hay deudas registradas.',
    payments: 'Historial de pagos',
    date: 'Fecha',
    receivable: 'Deuda',
    method: 'Método',
    amount: 'Monto',
    noPayments: 'Aún no hay pagos registrados.',
    footer: (page: number, pages: number) => `Generado por Solvia  |  Página ${page} de ${pages}`,
    fileName: 'estado-de-cuenta',
    methods: { yape: 'Yape', plin: 'Plin', cash: 'Efectivo', bank_transfer: 'Transferencia' },
    statuses: { pending: 'Pendiente', partial: 'Parcial', paid: 'Pagada', overdue: 'Vencida' },
  },
} satisfies Record<Locale, unknown>;

export const statementService = {
  /** Builds the PDF account statement for a customer of the current tenant. */
  async generatePdf(customerId: string) {
    const [tenant, customer] = await Promise.all([
      tenantRepository.findCurrent(),
      customerRepository.findByIdWithHistory(customerId),
    ]);
    if (!customer) throw AppError.notFound('Customer');
    if (!tenant) throw AppError.notFound('Tenant');

    const text = STRINGS[currentLocale()];
    const currency = env.CURRENCY;
    const money = (value: number) => formatMoney(value, currency);
    const today = todayInTimezone(env.APP_TIMEZONE);

    const receivables = customer.receivables.map((receivable) => {
      const totalAmount = toNumber(receivable.totalAmount);
      const paidAmount = toNumber(receivable.paidAmount);
      return {
        ...receivable,
        totalAmount,
        paidAmount,
        outstanding: outstandingAmount({ totalAmount, paidAmount }),
      };
    });
    const payments = customer.receivables
      .flatMap((receivable) => receivable.payments.map((payment) => ({ ...payment, receivable })))
      .sort((a, b) => b.date.getTime() - a.date.getTime());

    const totals = {
      billed: roundMoney(receivables.reduce((sum, item) => sum + item.totalAmount, 0)),
      paid: roundMoney(receivables.reduce((sum, item) => sum + item.paidAmount, 0)),
      outstanding: roundMoney(receivables.reduce((sum, item) => sum + item.outstanding, 0)),
      overdue: roundMoney(
        receivables
          .filter((item) => item.status === 'overdue')
          .reduce((sum, item) => sum + item.outstanding, 0),
      ),
    };

    const buffer = await renderToBuffer((doc) => {
      drawHeader(doc, {
        tagline: text.tagline,
        title: text.title,
        subtitle: `${tenant.name}  |  ${formatDisplayDate(today)}`,
      });

      doc.font('Helvetica-Bold').fontSize(11).text(text.customer);
      doc.font('Helvetica').fontSize(10).fillColor(TEXT_COLOR).text(customer.name);
      doc.fillColor(MUTED_COLOR).text(customer.phone);
      if (customer.documentId) doc.text(`${text.id}: ${customer.documentId}`);
      doc.fillColor(TEXT_COLOR);

      drawSectionTitle(doc, text.summary);
      drawTable(
        doc,
        [
          { header: text.billed, width: 124, align: 'right' },
          { header: text.paid, width: 124, align: 'right' },
          { header: text.outstanding, width: 124, align: 'right' },
          { header: text.overdue, width: 123, align: 'right' },
        ],
        [
          [
            money(totals.billed),
            money(totals.paid),
            money(totals.outstanding),
            money(totals.overdue),
          ],
        ],
        '',
      );

      drawSectionTitle(doc, text.receivables);
      drawTable(
        doc,
        [
          { header: text.description, width: 115 },
          { header: text.issued, width: 68 },
          { header: text.due, width: 70 },
          { header: text.total, width: 60, align: 'right' },
          { header: text.paidShort, width: 60, align: 'right' },
          { header: text.balance, width: 64, align: 'right' },
          { header: text.status, width: 58 },
        ],
        receivables.map((item) => [
          item.description,
          formatDisplayDate(item.issueDate),
          formatDisplayDate(item.dueDate),
          money(item.totalAmount),
          money(item.paidAmount),
          money(item.outstanding),
          text.statuses[item.status],
        ]),
        text.noReceivables,
      );

      drawSectionTitle(doc, text.payments);
      drawTable(
        doc,
        [
          { header: text.date, width: 90 },
          { header: text.receivable, width: 215 },
          { header: text.method, width: 90 },
          { header: text.amount, width: 100, align: 'right' },
        ],
        payments.map((payment) => [
          formatDisplayDate(payment.date),
          payment.receivable.description,
          text.methods[payment.method],
          money(toNumber(payment.amount)),
        ]),
        text.noPayments,
      );

      drawFooters(doc, text.footer);
    });

    const safeName = customer.name.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
    return {
      buffer,
      fileName: `solvia-${text.fileName}-${safeName}.pdf`,
      customer,
      tenant,
      totals,
      today,
    };
  },

  /**
   * Generates the statement, stores it and sends it to the customer via WhatsApp.
   * `receivableId` links the notification log entry; defaults to the most recent receivable.
   */
  async sendStatement(customerId: string, receivableId?: string) {
    const { buffer, customer, tenant, totals, today } = await this.generatePdf(customerId);
    const linkedReceivableId = receivableId ?? customer.receivables[0]?.id;
    if (!linkedReceivableId) {
      throw new AppError(
        422,
        'NO_RECEIVABLES_TO_REPORT',
        'The customer has no receivables to report',
      );
    }

    const relativeUrl = await storageService.saveStatement(buffer);
    const statementUrl = storageService.toAbsoluteUrl(relativeUrl);
    const notification = await notificationService.sendWhatsApp({
      receivableId: linkedReceivableId,
      to: customer.phone,
      templateType: 'statement',
      templateText: await settingsService.getTemplateText('statement'),
      variables: {
        name: customer.name,
        business: tenant.name,
        amount: formatMoney(totals.outstanding, env.CURRENCY),
        date: formatDisplayDate(today),
        statementUrl,
      },
    });
    // Without a real provider nothing reaches the customer: hand back a click-to-chat link with
    // the same message so the user can send it from their own WhatsApp.
    const whatsappUrl =
      whatsAppProvider.name === 'mock'
        ? whatsAppChatUrl(customer.phone, notification.sentContent)
        : undefined;
    return { statementUrl: relativeUrl, notification, whatsappUrl };
  },
};
