import PDFDocument from 'pdfkit';
import { env } from '../config/env';
import { outstandingAmount } from '../domain/receivableStatus';
import { AppError } from '../errors/AppError';
import { formatDisplayDate, todayInTimezone } from '../lib/dates';
import { currentLocale, type Locale } from '../lib/locale';
import { formatMoney, roundMoney, toNumber } from '../lib/money';
import { customerRepository } from '../repositories/customer.repository';
import { tenantRepository } from '../repositories/tenant.repository';
import { whatsAppProvider } from '../providers/whatsapp';
import { notificationService } from './notification.service';
import { settingsService } from './settings.service';
import { storageService } from './storage.service';

type PdfDoc = InstanceType<typeof PDFDocument>;

const BRAND_COLOR = '#0F766E';
const TEXT_COLOR = '#1F2937';
const MUTED_COLOR = '#6B7280';
const BORDER_COLOR = '#E5E7EB';
const PAGE_MARGIN = 50;

interface Column {
  header: string;
  width: number;
  align?: 'left' | 'right';
}

/** Every text printed on the statement, in each supported language. */
const STRINGS = {
  en: {
    tagline: 'Credit & collections',
    title: 'Account Statement',
    customer: 'Customer',
    id: 'ID',
    summary: 'Summary',
    billed: 'Total billed',
    paid: 'Total paid',
    outstanding: 'Outstanding',
    overdue: 'Overdue',
    receivables: 'Receivables',
    description: 'Description',
    issued: 'Issued',
    due: 'Due',
    total: 'Total',
    paidShort: 'Paid',
    balance: 'Balance',
    status: 'Status',
    noReceivables: 'No receivables registered.',
    payments: 'Payment history',
    date: 'Date',
    receivable: 'Receivable',
    method: 'Method',
    amount: 'Amount',
    noPayments: 'No payments registered yet.',
    footer: (page: number, pages: number) => `Generated by Solvia  |  Page ${page} of ${pages}`,
    fileName: 'statement',
    methods: { yape: 'Yape', plin: 'Plin', cash: 'Cash', bank_transfer: 'Bank transfer' },
    statuses: { pending: 'Pending', partial: 'Partial', paid: 'Paid', overdue: 'Overdue' },
  },
  es: {
    tagline: 'Créditos y cobranzas',
    title: 'Estado de cuenta',
    customer: 'Cliente',
    id: 'Doc.',
    summary: 'Resumen',
    billed: 'Total facturado',
    paid: 'Total pagado',
    outstanding: 'Saldo pendiente',
    overdue: 'Vencido',
    receivables: 'Deudas',
    description: 'Descripción',
    issued: 'Emisión',
    due: 'Vencimiento',
    total: 'Total',
    paidShort: 'Pagado',
    balance: 'Saldo',
    status: 'Estado',
    noReceivables: 'No hay deudas registradas.',
    payments: 'Historial de pagos',
    date: 'Fecha',
    receivable: 'Deuda',
    method: 'Método',
    amount: 'Monto',
    noPayments: 'Aún no hay pagos registrados.',
    footer: (page: number, pages: number) => `Generado por Solvia  |  Página ${page} de ${pages}`,
    fileName: 'estado-de-cuenta',
    methods: { yape: 'Yape', plin: 'Plin', cash: 'Efectivo', bank_transfer: 'Transferencia' },
    statuses: { pending: 'Pendiente', partial: 'Parcial', paid: 'Pagada', overdue: 'Vencida' },
  },
} satisfies Record<Locale, unknown>;

type Strings = (typeof STRINGS)[Locale];

/** Click-to-chat link that opens WhatsApp with `text` ready to send to `phone` (E.164). */
function whatsAppChatUrl(phone: string, text: string) {
  return `https://wa.me/${phone.replace(/\D/g, '')}?text=${encodeURIComponent(text)}`;
}

function renderToBuffer(build: (doc: PdfDoc) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    try {
      build(doc);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Solvia mark geometry (64x64): Soli the owl + gold S/ coin. Same values as the web logo
 * (src/ui/brand/owlGeometry.ts in the frontend repositories).
 */
const LOGO = {
  head: 'M13 17C13.5 14.5 16 13.8 18 15L24 19.6C26.5 18.9 29.2 18.5 32 18.5C34.8 18.5 37.5 18.9 40 19.6L46 15C48 13.8 50.5 14.5 51 17L51.5 29.5C52.5 32 53 34.7 53 37.5C53 47.7 43.6 54.5 32 54.5C20.4 54.5 11 47.7 11 37.5C11 34.7 11.5 32 12.5 29.5Z',
  brows: ['M17 27.4Q23.5 23.6 29.6 26.4', 'M34.4 26.4Q40.5 23.6 47 27.4'],
  beak: 'M32 41.6C30.4 41.6 29 42.6 29 43.9C29 45.6 30.8 47.3 32 48C33.2 47.3 35 45.6 35 43.9C35 42.6 33.6 41.6 32 41.6Z',
  coinS:
    'M50.4 45.6C49.7 44.8 48.8 44.4 47.7 44.4C46.1 44.4 45.1 45.2 45.1 46.4C45.1 47.7 46.3 48 47.8 48.3C49.4 48.6 50.5 49 50.5 50.3C50.5 51.5 49.4 52.3 47.8 52.3C46.6 52.3 45.7 51.9 45.1 51.1',
  coinSlash: 'M54.4 43.8L52 54',
};

/** Draws the Solvia logo mark at (x, y) with the given size. */
function drawLogoMark(doc: PdfDoc, x: number, y: number, size: number) {
  doc.save();
  doc.translate(x, y).scale(size / 64);
  const background = doc.linearGradient(4, 2, 60, 62);
  background.stop(0, '#34d399').stop(0.5, '#0d9488').stop(1, '#0c3a47');
  doc.roundedRect(0, 0, 64, 64, 18).fill(background);
  doc.path(LOGO.head).fill('#f0fdfa');
  for (const brow of LOGO.brows) {
    doc.path(brow).lineWidth(2.3).lineCap('round').stroke('#0d9488');
  }
  doc.fillOpacity(0.5);
  doc.ellipse(15.8, 45, 3.3, 2).fill('#fb7185');
  doc.ellipse(48.2, 45, 3.3, 2).fill('#fb7185');
  doc.fillOpacity(1);
  for (const cx of [23.5, 40.5]) {
    doc.circle(cx, 38, 9.2).fill('#a7f3d0');
    doc.circle(cx, 38, 6.4).fill('#0b2530');
    doc.circle(cx + 2.2, 35.7, 2.3).fill('#ffffff');
    doc.circle(cx - 2.1, 40.3, 1).fill('#ffffff');
  }
  doc.path(LOGO.beak).fill('#f59e0b');
  const gold = doc.linearGradient(40, 40, 58, 58);
  gold.stop(0, '#fde68a').stop(1, '#f59e0b');
  doc.circle(49, 49, 9.5).lineWidth(2.5).fillAndStroke(gold, '#0c3a47');
  doc.path(LOGO.coinS).lineWidth(1.8).lineCap('round').lineJoin('round').stroke('#92400e');
  doc.path(LOGO.coinSlash).lineWidth(1.8).lineCap('round').stroke('#92400e');
  doc.restore();
}

function drawHeader(doc: PdfDoc, text: Strings, businessName: string, generatedOn: Date) {
  const width = doc.page.width;
  doc.rect(0, 0, width, 90).fill(BRAND_COLOR);
  drawLogoMark(doc, PAGE_MARGIN, 23, 44);
  const textX = PAGE_MARGIN + 56;
  doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(24).text('Solvia', textX, 26);
  doc.font('Helvetica').fontSize(10).fillColor('#CCFBF1').text(text.tagline, textX, 54);
  doc.fillColor('#FFFFFF');
  doc
    .font('Helvetica-Bold')
    .fontSize(14)
    .text(text.title, PAGE_MARGIN, 30, { width: width - PAGE_MARGIN * 2, align: 'right' });
  doc
    .font('Helvetica')
    .fontSize(10)
    .text(`${businessName}  |  ${formatDisplayDate(generatedOn)}`, PAGE_MARGIN, 52, {
      width: width - PAGE_MARGIN * 2,
      align: 'right',
    });
  doc.fillColor(TEXT_COLOR);
  doc.y = 115;
}

function drawSectionTitle(doc: PdfDoc, title: string) {
  ensureSpace(doc, 40);
  doc.moveDown(0.8);
  doc.font('Helvetica-Bold').fontSize(12).fillColor(BRAND_COLOR).text(title, PAGE_MARGIN);
  doc.moveDown(0.4);
  doc.fillColor(TEXT_COLOR);
}

function ensureSpace(doc: PdfDoc, height: number) {
  if (doc.y + height > doc.page.height - PAGE_MARGIN - 20) {
    doc.addPage();
    doc.y = PAGE_MARGIN;
  }
}

function drawRow(
  doc: PdfDoc,
  columns: Column[],
  values: string[],
  options: { bold?: boolean; fill?: string },
) {
  const rowHeight = 20;
  ensureSpace(doc, rowHeight);
  const top = doc.y;
  const tableWidth = columns.reduce((sum, column) => sum + column.width, 0);
  if (options.fill) {
    doc.rect(PAGE_MARGIN, top, tableWidth, rowHeight).fill(options.fill);
  }
  doc
    .font(options.bold ? 'Helvetica-Bold' : 'Helvetica')
    .fontSize(9)
    .fillColor(TEXT_COLOR);
  let x = PAGE_MARGIN;
  columns.forEach((column, index) => {
    doc.text(values[index] ?? '', x + 4, top + 6, {
      width: column.width - 8,
      align: column.align ?? 'left',
      lineBreak: false,
      ellipsis: true,
    });
    x += column.width;
  });
  doc
    .moveTo(PAGE_MARGIN, top + rowHeight)
    .lineTo(PAGE_MARGIN + tableWidth, top + rowHeight)
    .strokeColor(BORDER_COLOR)
    .lineWidth(0.5)
    .stroke();
  doc.y = top + rowHeight;
}

function drawTable(doc: PdfDoc, columns: Column[], rows: string[][], emptyMessage: string) {
  drawRow(
    doc,
    columns,
    columns.map((column) => column.header),
    { bold: true, fill: '#F3F4F6' },
  );
  if (rows.length === 0) {
    doc
      .moveDown(0.5)
      .font('Helvetica-Oblique')
      .fontSize(9)
      .fillColor(MUTED_COLOR)
      .text(emptyMessage, PAGE_MARGIN);
    doc.fillColor(TEXT_COLOR);
    return;
  }
  for (const row of rows) {
    drawRow(doc, columns, row, {});
  }
}

function drawFooters(doc: PdfDoc, text: Strings) {
  const range = doc.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    // The footer sits inside the bottom margin; lift the margin while writing it, otherwise
    // pdfkit treats the text as overflow and appends an empty page.
    const bottomMargin = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor(MUTED_COLOR)
      .text(text.footer(index + 1, range.count), PAGE_MARGIN, doc.page.height - PAGE_MARGIN + 10, {
        width: doc.page.width - PAGE_MARGIN * 2,
        align: 'center',
        lineBreak: false,
      });
    doc.page.margins.bottom = bottomMargin;
  }
}

export const statementService = {
  /** Builds the PDF account statement for a customer of the current tenant. */
  async generatePdf(customerId: string) {
    const [tenant, customer] = await Promise.all([
      tenantRepository.findCurrent(),
      customerRepository.findByIdWithHistory(customerId),
    ]);
    if (!customer) throw AppError.notFound('Customer');
    if (!tenant) throw AppError.notFound('Tenant');

    const text = STRINGS[currentLocale()];
    const currency = env.CURRENCY;
    const money = (value: number) => formatMoney(value, currency);
    const today = todayInTimezone(env.APP_TIMEZONE);

    const receivables = customer.receivables.map((receivable) => {
      const totalAmount = toNumber(receivable.totalAmount);
      const paidAmount = toNumber(receivable.paidAmount);
      return {
        ...receivable,
        totalAmount,
        paidAmount,
        outstanding: outstandingAmount({ totalAmount, paidAmount }),
      };
    });
    const payments = customer.receivables
      .flatMap((receivable) => receivable.payments.map((payment) => ({ ...payment, receivable })))
      .sort((a, b) => b.date.getTime() - a.date.getTime());

    const totals = {
      billed: roundMoney(receivables.reduce((sum, item) => sum + item.totalAmount, 0)),
      paid: roundMoney(receivables.reduce((sum, item) => sum + item.paidAmount, 0)),
      outstanding: roundMoney(receivables.reduce((sum, item) => sum + item.outstanding, 0)),
      overdue: roundMoney(
        receivables
          .filter((item) => item.status === 'overdue')
          .reduce((sum, item) => sum + item.outstanding, 0),
      ),
    };

    const buffer = await renderToBuffer((doc) => {
      drawHeader(doc, text, tenant.name, today);

      doc.font('Helvetica-Bold').fontSize(11).text(text.customer);
      doc.font('Helvetica').fontSize(10).fillColor(TEXT_COLOR).text(customer.name);
      doc.fillColor(MUTED_COLOR).text(customer.phone);
      if (customer.documentId) doc.text(`${text.id}: ${customer.documentId}`);
      doc.fillColor(TEXT_COLOR);

      drawSectionTitle(doc, text.summary);
      drawTable(
        doc,
        [
          { header: text.billed, width: 124, align: 'right' },
          { header: text.paid, width: 124, align: 'right' },
          { header: text.outstanding, width: 124, align: 'right' },
          { header: text.overdue, width: 123, align: 'right' },
        ],
        [
          [
            money(totals.billed),
            money(totals.paid),
            money(totals.outstanding),
            money(totals.overdue),
          ],
        ],
        '',
      );

      drawSectionTitle(doc, text.receivables);
      drawTable(
        doc,
        [
          { header: text.description, width: 115 },
          { header: text.issued, width: 68 },
          { header: text.due, width: 70 },
          { header: text.total, width: 60, align: 'right' },
          { header: text.paidShort, width: 60, align: 'right' },
          { header: text.balance, width: 64, align: 'right' },
          { header: text.status, width: 58 },
        ],
        receivables.map((item) => [
          item.description,
          formatDisplayDate(item.issueDate),
          formatDisplayDate(item.dueDate),
          money(item.totalAmount),
          money(item.paidAmount),
          money(item.outstanding),
          text.statuses[item.status],
        ]),
        text.noReceivables,
      );

      drawSectionTitle(doc, text.payments);
      drawTable(
        doc,
        [
          { header: text.date, width: 90 },
          { header: text.receivable, width: 215 },
          { header: text.method, width: 90 },
          { header: text.amount, width: 100, align: 'right' },
        ],
        payments.map((payment) => [
          formatDisplayDate(payment.date),
          payment.receivable.description,
          text.methods[payment.method],
          money(toNumber(payment.amount)),
        ]),
        text.noPayments,
      );

      drawFooters(doc, text);
    });

    const safeName = customer.name.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
    return {
      buffer,
      fileName: `solvia-${text.fileName}-${safeName}.pdf`,
      customer,
      tenant,
      totals,
      today,
    };
  },

  /**
   * Generates the statement, stores it and sends it to the customer via WhatsApp.
   * `receivableId` links the notification log entry; defaults to the most recent receivable.
   */
  async sendStatement(customerId: string, receivableId?: string) {
    const { buffer, customer, tenant, totals, today } = await this.generatePdf(customerId);
    const linkedReceivableId = receivableId ?? customer.receivables[0]?.id;
    if (!linkedReceivableId) {
      throw new AppError(
        422,
        'NO_RECEIVABLES_TO_REPORT',
        'The customer has no receivables to report',
      );
    }

    const relativeUrl = await storageService.saveStatement(buffer);
    const statementUrl = storageService.toAbsoluteUrl(relativeUrl);
    const notification = await notificationService.sendWhatsApp({
      receivableId: linkedReceivableId,
      to: customer.phone,
      templateType: 'statement',
      templateText: await settingsService.getTemplateText('statement'),
      variables: {
        name: customer.name,
        business: tenant.name,
        amount: formatMoney(totals.outstanding, env.CURRENCY),
        date: formatDisplayDate(today),
        statementUrl,
      },
    });
    // Without a real provider nothing reaches the customer: hand back a click-to-chat link with
    // the same message so the user can send it from their own WhatsApp.
    const whatsappUrl =
      whatsAppProvider.name === 'mock'
        ? whatsAppChatUrl(customer.phone, notification.sentContent)
        : undefined;
    return { statementUrl: relativeUrl, notification, whatsappUrl };
  },
};
